"""Add KnowledgeChunk and cascade deletes

Revision ID: 223c9a80e1d9
Revises: aca552abd3f1
Create Date: 2026-05-28 18:41:10.577526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '223c9a80e1d9'
down_revision: Union[str, None] = 'aca552abd3f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('integration_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_id'), 'knowledge_chunks', ['id'], unique=False)
    op.drop_constraint(op.f('agent_tools_integration_id_fkey'), 'agent_tools', type_='foreignkey')
    op.create_foreign_key(None, 'agent_tools', 'integrations', ['integration_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('knowledge_documents_integration_id_fkey'), 'knowledge_documents', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_documents', 'integrations', ['integration_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_documents', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_documents_integration_id_fkey'), 'knowledge_documents', 'integrations', ['integration_id'], ['id'])
    op.drop_constraint(None, 'agent_tools', type_='foreignkey')
    op.create_foreign_key(op.f('agent_tools_integration_id_fkey'), 'agent_tools', 'integrations', ['integration_id'], ['id'])
    op.drop_index(op.f('ix_knowledge_chunks_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    # ### end Alembic commands ###
