"""add run_type to runs

Revision ID: 2be32f66c1b4
Revises: 939130fc0794
Create Date: 2026-05-30 15:04:33.256459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be32f66c1b4'
down_revision: Union[str, None] = '939130fc0794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('run_type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_runs_run_type'), 'runs', ['run_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_run_type'), table_name='runs')
    op.drop_column('runs', 'run_type')
    # ### end Alembic commands ###
