"""add app_connections

Revision ID: 5ab384814bc7
Revises: 857f88b1b394
Create Date: 2026-05-29 17:56:05.831518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ab384814bc7'
down_revision: Union[str, None] = '857f88b1b394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('SLACK', 'TELEGRAM', 'JIRA', 'CONFLUENCE', 'GOOGLE_DRIVE', 'CUSTOM_WEBHOOK', name='appconnectiontype'), nullable=True),
    sa.Column('credentials', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_connections_id'), 'app_connections', ['id'], unique=False)
    op.create_index(op.f('ix_app_connections_name'), 'app_connections', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_connections_name'), table_name='app_connections')
    op.drop_index(op.f('ix_app_connections_id'), table_name='app_connections')
    op.drop_table('app_connections')
    # ### end Alembic commands ###
