"""add multi-tenancy

Revision ID: 7265461d2805
Revises: a7e2350e2772
Create Date: 2026-05-29 19:05:37.299392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7265461d2805'
down_revision: Union[str, None] = '89b4c935e0ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('agent_tools', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agent_tools', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('agents', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agents', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('app_connections', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'app_connections', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('integrations', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'integrations', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('knowledge_chunks', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'knowledge_chunks', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('knowledge_documents', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'knowledge_documents', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('runs', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'runs', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('uploaded_files', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'uploaded_files', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('workflows', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workflows', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    
    # --- MANUAL BACKFILL SCRIPT ---
    import bcrypt
    salt = bcrypt.gensalt()
    hashed_pwd = bcrypt.hashpw("admin".encode('utf-8'), salt).decode('utf-8')
    
    # Insert system organization
    op.execute("INSERT INTO organizations (name) VALUES ('System')")
    
    # Insert default user
    op.execute(f"INSERT INTO users (organization_id, email, hashed_password, is_active) VALUES ((SELECT id FROM organizations WHERE name = 'System' LIMIT 1), 'admin@system.local', '{hashed_pwd}', true)")

    # Backfill organization_id in all tables
    tables = [
        'agent_tools', 'agents', 'app_connections', 'integrations',
        'knowledge_chunks', 'knowledge_documents', 'runs', 'uploaded_files', 'workflows'
    ]
    for table in tables:
        op.execute(f"UPDATE {table} SET organization_id = (SELECT id FROM organizations WHERE name = 'System' LIMIT 1) WHERE organization_id IS NULL")
        op.alter_column(table, 'organization_id', existing_type=sa.Integer(), nullable=False)
    # ------------------------------
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.drop_column('workflows', 'organization_id')
    op.drop_constraint(None, 'uploaded_files', type_='foreignkey')
    op.drop_column('uploaded_files', 'organization_id')
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.drop_column('runs', 'organization_id')
    op.drop_constraint(None, 'knowledge_documents', type_='foreignkey')
    op.drop_column('knowledge_documents', 'organization_id')
    op.drop_constraint(None, 'knowledge_chunks', type_='foreignkey')
    op.drop_column('knowledge_chunks', 'organization_id')
    op.drop_constraint(None, 'integrations', type_='foreignkey')
    op.drop_column('integrations', 'organization_id')
    op.drop_constraint(None, 'app_connections', type_='foreignkey')
    op.drop_column('app_connections', 'organization_id')
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_column('agents', 'organization_id')
    op.drop_constraint(None, 'agent_tools', type_='foreignkey')
    op.drop_column('agent_tools', 'organization_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
