"""pivot_triggers_and_templates

Revision ID: 939130fc0794
Revises: cbe65c0fbd59
Create Date: 2026-05-30 13:14:39.192153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '939130fc0794'
down_revision: Union[str, None] = 'cbe65c0fbd59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_workflow_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('graph_definition', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_default_workflow_templates_id'), 'default_workflow_templates', ['id'], unique=False)
    op.create_index(op.f('ix_default_workflow_templates_name'), 'default_workflow_templates', ['name'], unique=False)
    op.create_table('workflow_triggers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_triggers_enabled'), 'workflow_triggers', ['enabled'], unique=False)
    op.create_index(op.f('ix_workflow_triggers_type'), 'workflow_triggers', ['type'], unique=False)
    op.add_column('runs', sa.Column('trigger_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_runs_trigger_id', 'runs', 'workflow_triggers', ['trigger_id'], ['id'], ondelete='SET NULL')
    
    # Delete old default workflows and their associated runs
    op.execute("DELETE FROM runs WHERE workflow_id IN (SELECT id FROM workflows WHERE name IN ('Customer Support Agent', 'Data Analysis Assistant', 'Research & Summarization', 'Job Search Agent'));")
    op.execute("DELETE FROM workflows WHERE name IN ('Customer Support Agent', 'Data Analysis Assistant', 'Research & Summarization', 'Job Search Agent');")
    
    # Seed new default templates
    templates_table = sa.table(
        'default_workflow_templates',
        sa.column('name', sa.String),
        sa.column('description', sa.String),
        sa.column('graph_definition', sa.JSON)
    )
    
    customer_support_graph = {
        "nodes": [
            {"id": "start", "type": "start", "position": {"x": 100, "y": 100}, "data": {"input_mapping": {"input": "$.text"}}},
            {"id": "agent", "type": "agent", "position": {"x": 300, "y": 100}, "data": {"system_prompt": "You are a customer support agent.", "tools": ["rag"]}},
            {"id": "router", "type": "router", "position": {"x": 500, "y": 100}, "data": {"condition": "Is human needed?"}},
            {"id": "human", "type": "humanPause", "position": {"x": 700, "y": 50}, "data": {}},
            {"id": "end", "type": "end", "position": {"x": 700, "y": 150}, "data": {"output_from": "output"}}
        ],
        "edges": [
            {"id": "e1", "source": "start", "target": "agent"},
            {"id": "e2", "source": "agent", "target": "router"},
            {"id": "e3", "source": "router", "target": "human", "condition": "yes"},
            {"id": "e4", "source": "router", "target": "end", "condition": "no"},
            {"id": "e5", "source": "human", "target": "end"}
        ]
    }
    
    web_research_graph = {
        "nodes": [
            {"id": "start", "type": "start", "position": {"x": 100, "y": 100}, "data": {"input_mapping": {"input": "$.query"}}},
            {"id": "agent", "type": "agent", "position": {"x": 300, "y": 100}, "data": {"system_prompt": "You are a web researcher.", "tools": ["web_search"]}},
            {"id": "end", "type": "end", "position": {"x": 500, "y": 100}, "data": {"output_from": "output"}}
        ],
        "edges": [
            {"id": "e1", "source": "start", "target": "agent"},
            {"id": "e2", "source": "agent", "target": "end"}
        ]
    }
    
    data_extraction_graph = {
        "nodes": [
            {"id": "start", "type": "start", "position": {"x": 100, "y": 100}, "data": {"input_mapping": {"input": "$.document"}}},
            {"id": "agent", "type": "agent", "position": {"x": 300, "y": 100}, "data": {"system_prompt": "Extract structured data as JSON.", "response_format": "json_object"}},
            {"id": "end", "type": "end", "position": {"x": 500, "y": 100}, "data": {"output_from": "output"}}
        ],
        "edges": [
            {"id": "e1", "source": "start", "target": "agent"},
            {"id": "e2", "source": "agent", "target": "end"}
        ]
    }

    op.bulk_insert(templates_table, [
        {"name": "Customer Support Triage", "description": "Handles inbound customer support requests with RAG and human handoff.", "graph_definition": customer_support_graph},
        {"name": "Web Research & Summarization", "description": "Searches the web and summarizes findings.", "graph_definition": web_research_graph},
        {"name": "Data Extraction", "description": "Extracts structured JSON data from text.", "graph_definition": data_extraction_graph}
    ])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.drop_column('runs', 'trigger_id')
    op.drop_index(op.f('ix_workflow_triggers_type'), table_name='workflow_triggers')
    op.drop_index(op.f('ix_workflow_triggers_enabled'), table_name='workflow_triggers')
    op.drop_table('workflow_triggers')
    op.drop_index(op.f('ix_default_workflow_templates_name'), table_name='default_workflow_templates')
    op.drop_index(op.f('ix_default_workflow_templates_id'), table_name='default_workflow_templates')
    op.drop_table('default_workflow_templates')
    # ### end Alembic commands ###
