"""use EncryptedJSON for app connections

Revision ID: a7e2350e2772
Revises: 5ab384814bc7
Create Date: 2026-05-29 18:22:05.332081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import backend.models

# revision identifiers, used by Alembic.
revision: str = 'a7e2350e2772'
down_revision: Union[str, None] = '5ab384814bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_connections', 'credentials',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=backend.models.EncryptedJSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_connections', 'credentials',
               existing_type=backend.models.EncryptedJSON(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
