"""update_run_schema

Revision ID: cbe65c0fbd59
Revises: d2g3h4j5k6l7
Create Date: 2026-05-30 12:39:03.509261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbe65c0fbd59'
down_revision: Union[str, None] = 'd2g3h4j5k6l7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_constraint(op.f('agent_tools_organization_id_fkey'), 'agent_tools', type_='foreignkey')
    op.drop_column('agent_tools', 'organization_id')
    op.drop_constraint(op.f('agents_organization_id_fkey'), 'agents', type_='foreignkey')
    op.drop_column('agents', 'organization_id')
    op.drop_constraint(op.f('app_connections_organization_id_fkey'), 'app_connections', type_='foreignkey')
    op.drop_column('app_connections', 'organization_id')
    op.drop_constraint(op.f('integrations_organization_id_fkey'), 'integrations', type_='foreignkey')
    op.drop_column('integrations', 'organization_id')
    op.drop_constraint(op.f('knowledge_chunks_organization_id_fkey'), 'knowledge_chunks', type_='foreignkey')
    op.drop_column('knowledge_chunks', 'organization_id')
    op.drop_constraint(op.f('knowledge_documents_organization_id_fkey'), 'knowledge_documents', type_='foreignkey')
    op.drop_column('knowledge_documents', 'organization_id')
    op.add_column('runs', sa.Column('input_data', sa.JSON(), nullable=True))
    op.add_column('runs', sa.Column('output_data', sa.JSON(), nullable=True))
    op.add_column('runs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('runs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('runs_organization_id_fkey'), 'runs', type_='foreignkey')
    op.drop_column('runs', 'organization_id')
    op.drop_constraint(op.f('uploaded_files_organization_id_fkey'), 'uploaded_files', type_='foreignkey')
    op.drop_column('uploaded_files', 'organization_id')
    op.drop_constraint(op.f('workflows_organization_id_fkey'), 'workflows', type_='foreignkey')
    op.drop_column('workflows', 'organization_id')
    
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('workflows_organization_id_fkey'), 'workflows', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('uploaded_files', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('uploaded_files_organization_id_fkey'), 'uploaded_files', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('runs', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('runs_organization_id_fkey'), 'runs', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_column('runs', 'completed_at')
    op.drop_column('runs', 'started_at')
    op.drop_column('runs', 'output_data')
    op.drop_column('runs', 'input_data')
    op.add_column('knowledge_documents', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('knowledge_documents_organization_id_fkey'), 'knowledge_documents', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('knowledge_chunks', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('knowledge_chunks_organization_id_fkey'), 'knowledge_chunks', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('integrations', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('integrations_organization_id_fkey'), 'integrations', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('app_connections', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('app_connections_organization_id_fkey'), 'app_connections', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('agents', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('agents_organization_id_fkey'), 'agents', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('agent_tools', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('agent_tools_organization_id_fkey'), 'agent_tools', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_table('organizations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('organizations_pkey'))
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('users_organization_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
